"""
Logging and telemetry setup.

Standardized setup for Weights & Biases (WandB) and file-based logging.
Supports offline modes and resolved configuration logging.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from omegaconf import OmegaConf, DictConfig

from gibbsq.core.config import ExperimentConfig
from gibbsq.utils.device import setup_jax

log = logging.getLogger(__name__)

try:
    import wandb
    from wandb.sdk.wandb_run import Run
except ImportError:
    wandb = None
    Run = None

def get_run_config(
    cfg: ExperimentConfig, 
    experiment_type: str, 
    raw_cfg: DictConfig | None = None
) -> tuple[Path, str]:
    """
    Generate a unique Run ID and prepare a 'Run Capsule' directory.
    
    The structure is: outputs/<experiment_type>/<run_name>_<timestamp>/
    
    Parameters
    ----------
    cfg : ExperimentConfig
        The root configuration.
    experiment_type : str
        The category of the experiment (e.g., 'policy_comparison').
    raw_cfg : DictConfig, optional
        The raw Hydra config for full YAML resolution.
        
    Returns
    -------
    tuple[Path, str]
        (run_dir, run_id)
    """
    # Initialize hardware acceleration if enabled (must be done early)
    setup_jax(cfg.jax)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = cfg.wandb.run_name or "run"
    run_id = f"{base_name}_{timestamp}"
    
    run_dir = Path(cfg.output_dir) / experiment_type / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    
    # ── File logging ────────────────────────────────────
    # Write logs to a file inside the run directory.
    capsule_log_dir = run_dir / "logs"
    capsule_log_dir.mkdir(parents=True, exist_ok=True)
    
    log_file = capsule_log_dir / "run.log"
    file_handler = logging.FileHandler(log_file)
    file_handler.setFormatter(logging.Formatter(
        '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    ))
    logging.getLogger().addHandler(file_handler)
    
    # Persist the resolved experiment config into the capsule for absolute traceability
    config_path = run_dir / "config.yaml"
    if raw_cfg is not None:
        OmegaConf.save(raw_cfg, config_path, resolve=True)
    else:
        OmegaConf.save(cfg, config_path)
    
    log.info(f"[IO] Run directory: {run_dir.absolute()}")
    return run_dir, run_id

def setup_wandb(
    cfg: ExperimentConfig, 
    raw_cfg: DictConfig | None = None,
    default_group: str = "default_experiment",
    run_id: str | None = None,
    run_dir: Path | None = None
) -> Run | None:
    """
    Initialize a WandB run from the ExperimentConfig.
    
    Parameters
    ----------
    cfg : ExperimentConfig
        The validated system-wide configuration.
    raw_cfg : DictConfig, optional
        The raw Hydra DictConfig for resolution.
    default_group : str
        Group name to use if not specified in cfg.
    run_id : str, optional
        The unique Run ID (if already generated by get_run_config).
        
    Returns
    -------
    Run or None
        The initialized WandB run object.
    """
    if not cfg.wandb.enabled or wandb is None:
        return None

    # Handle Offline Mode
    if cfg.wandb.mode == "offline":
        os.environ["WANDB_MODE"] = "offline"
        log.info("[Logging] WandB offline mode.")
    elif cfg.wandb.mode == "disabled":
        os.environ["WANDB_MODE"] = "disabled"
        return None
    else:
        os.environ["WANDB_MODE"] = "online"

    # Resolve configuration
    if raw_cfg is not None:
        full_config = OmegaConf.to_container(raw_cfg, resolve=True)
    else:
        full_config = OmegaConf.to_container(OmegaConf.create(cfg), resolve=True)

    # Use existing run_id or fallback to cfg
    final_run_name = run_id or cfg.wandb.run_name

    run = wandb.init(
        project=cfg.wandb.project,
        entity=cfg.wandb.entity,
        group=cfg.wandb.group or default_group,
        tags=cfg.wandb.tags,
        name=final_run_name,
        config=full_config,
        dir=str(run_dir) if run_dir else None,
    )
    
    if run is not None:
        log.info(f"[Logging] WandB Run Linked: {run.name} ({cfg.wandb.mode})")
    
    return run
